### ISSUE TITLE
MIRA and tufts_models bugs that need to be fixed for T-DIL release candidate

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/trove#178]
- [x] MIRA Batch Publish from batch status page: https://github.com/curationexperts/mira/issues/289
- [x] MIRA Broken thumbnails for non-image objects: https://github.com/curationexperts/mira/issues/290
- [x] MIRA Capistrano Resque config issues: https://github.com/curationexperts/mira/issues/291
- [x] MIRA Pagination fails over 100: https://github.com/curationexperts/mira/issues/293
- [x] MIRA Importer pid validation: https://github.com/curationexperts/mira/issues/292

---
- [x] tufts_models pre-filtering #174 
- [x] art & art history (aah) pid formats #175
