### ISSUE TITLE
Document ActiveFedora & OM Namespace behavior

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/trove#87]
## Given
- XML **Datastream A** with no default name space and explicit name spacing on all terms (i.e. mixed namespaces, no default)
- XML **Datastream B** with the same terms as A, defining a default name space for the most common namespace, all terms are still explicitly prefixed (i.e. mixed namespaces with a redundant default defined)
- XML **Datastream C** with the same terms as A & B, but using default name spacing for the most common namespace, only terms not in the default namespace have prefixes (i.e. mixed namespaces with one as default, some terms not prefixed)
- XML **Datastream D** with a subset of the terms from C including only the terms in the default name space, uses only default namespace, no prefixes (i.e. datastream only uses terms from a single default namespace)

**AND**
- **Terminology 1** without a default namespace, explicitly defines all namespaces, explicitly prefixes all terms with the appropriate namespace
- **Terminology 2** with a default namespace, also explicitly defines all namespaces, explicitly prefixes all terms with the appropriate namespace
- **Terminology 3** with a default namespace, only defines other namespaces explicitly, only explicitly prefixes terms not in default namespace
- **Terminology 4** with default namespace only, all terms use default namespace
## QUESTION

Which data streams can each terminology successfully read and/or write:

|  | Datastream A | Datastream B | Datastream C | Datastream D |
| --- | --- | --- | --- | --- |
| Terminology 1 | RW | ?RW? | ? | X |
| Terminology 2 | ?RW? | RW | ?RW? | ?R? |
| Terminology 3 | ?X? | ?R? | RW | ?R? |
| Terminology 4 | X | X | X | RW |
## THOUGHTS

I think what tufts has is **Terminology 3** managing data streams like **Datastream C**.  We could minimize data compatibility issues if we can find a way to make **Terminology 2** read all four types of data streams and write data streams in **Datastream A** format.  Tufts would probably still have to make minor upgrades to `tuftsification-hydra`, but we probably wouldn't need to do a data migration on the entire repo.  **Terminology 4** and **Datastream D** are probably not necessary to deal with for the real world application, but I put them in for completeness of the the though exercise - we can probably ignore that column and row.  
## TODO
- [ ] Read through this ticket and update anything that's unclear
- [ ] Create a sample XML document with multiple namespaces that can be used for testing - probably any reasonably complete TuftsDcDetailed sample would work - see the datastream definition: https://github.com/TuftsUniversity/tuftsification-hydra/blob/master/app/models/datastreams/tufts_dc_detailed.rb
- [ ] Manually create versions of the sample XML that match each of the datastream configurations above
- [ ] Write code for each of the terminologies listed
- [ ] Figure out how the terminology actually behaves with an actual datastream and resolve the question marks in the table
